name: eShopOnWeb Build and Test

env:
  RESOURCE-GROUP: Kingb_Group
  LOCATION: Eastus
  TEMPLATE-FILE: infra/webapp.bicep
  SUBSCRIPTION-ID: 88042d0a-7b6c-418e-bdac-cbed1afd23d4
  WEBAPP-NAME: eshoponweb-webapp-Kingb

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v5

      # Prepare runner for desired .NET version SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
          dotnet-quality: "preview"

      # Build/Test/Publish the .NET project
      - name: Build with dotnet
        run: dotnet build ./eShopOnWeb.sln --configuration Release

      - name: Test with dotnet
        run: dotnet test ./eShopOnWeb.sln --configuration Release

      - name: dotnet publish
        run: |
          dotnet publish ./src/Web/Web.csproj -c Release -o ${{ env.DOTNET_ROOT }}/myapp
          cd ${{ env.DOTNET_ROOT }}/myapp
          zip -r ../app.zip .

      # Upload the published website code artifacts
      - name: Upload .NET app artifact
        uses: actions/upload-artifact@v5
        with:
          name: .net-app
          path: ${{ env.DOTNET_ROOT }}/app.zip

      # Upload the Bicep template as artifact for next job
      - name: Upload Bicep template artifact
        uses: actions/upload-artifact@v5
        with:
          name: bicep-template
          path: ${{ env.TEMPLATE-FILE }}

  # Use Bicep to deploy infrastructure + Publish webapp
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: "Development"
    steps:
      # Download the publish files created in previous job
      - name: Download .NET app artifact
        uses: actions/download-artifact@v6
        with:
          name: .net-app
          path: .net-app

      # Download the Bicep templates from previous job
      - name: Download Bicep template artifact
        uses: actions/download-artifact@v6
        with:
          name: bicep-template
          path: bicep-template

      # Login to Azure subscription using a service principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Azure WebApp using Bicep file
      - name: Deploy infrastructure
        uses: azure/arm-deploy@v2
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: bicep-template/webapp.bicep
          parameters: "webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}"
          failOnStdErr: false

      # Publish website to Azure App Service (WebApp)
      # Step disabled due to issue where the site sometimes can't be found
     
